name       : ibus-hangul
version    : 1.5.1
release    : 3
source     :
    - https://github.com/choehwanjin/ibus-hangul/archive/1.5.1.tar.gz : 8050753f1cdc5f502abbf0022b6a4552658c540ccea9ab36c919b752cf1e3a49
license    : GPL-2.0
component  : desktop.core
summary    : ibus-hangul is a Korean input method engine for IBus.
description: |
    ibus-hangul is a Korean input method engine for IBus.
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libhangul)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
